create table test_1 ( t bigint , a bigint ) STORED AS TEXTFILE;

-- Windows that do not include the CURRENT ROW.
--
LOAD DATA LOCAL INPATH '../../data/files/ptf_windows_no_curr_row_1.txt' INTO TABLE test_1;

EXPLAIN
SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS sum_a 
FROM test_1;

SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS sum_a 
FROM test_1;

EXPLAIN
SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 2 PRECEDING AND 1 PRECEDING) AS sum_a 
FROM test_1;

SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 2 PRECEDING AND 1 PRECEDING) AS sum_a 
FROM test_1;

EXPLAIN
SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 2 PRECEDING AND 2 PRECEDING) AS sum_a 
FROM test_1;

SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 2 PRECEDING AND 2 PRECEDING) AS sum_a 
FROM test_1;



EXPLAIN
SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) AS sum_a 
FROM test_1;

SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) AS sum_a 
FROM test_1;

EXPLAIN
SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 1 FOLLOWING AND 2 FOLLOWING) AS sum_a 
FROM test_1;

SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 1 FOLLOWING AND 2 FOLLOWING) AS sum_a 
FROM test_1;

EXPLAIN
SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 2 FOLLOWING AND 2 FOLLOWING) AS sum_a 
FROM test_1;

SELECT t, 
a, 
sum(a) OVER (PARTITION BY t,a ORDER BY a ROWS BETWEEN 2 FOLLOWING AND 2 FOLLOWING) AS sum_a 
FROM test_1;